# Generated by Django 4.0.1 on 2022-05-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='name',
            field=models.CharField(default='Default', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
