# Generated by Django 4.0.1 on 2022-05-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_articles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
            preserve_default=False,
        ),
    ]
