# Generated by Django 4.0.1 on 2022-05-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_categories_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='required',
            field=models.ManyToManyField(blank=True, to='course.Articles'),
        ),
    ]
