# Generated by Django 4.0.1 on 2022-05-11 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_articles_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth')], max_length=1)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('shortDescr', models.TextField(verbose_name='ShortDescr')),
                ('fullDescr', models.TextField(verbose_name='FullDescr')),
                ('neededThemes', models.ManyToManyField(blank=True, to='course.Articles')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
