# Generated by Django 4.0.1 on 2022-05-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_articles_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('shortDescr', models.TextField(verbose_name='ShortDescr')),
                ('fullDescr', models.TextField(verbose_name='FullDescr')),
                ('neededThemes', models.ManyToManyField(blank=True, to='course.Articles')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
