# Generated by Django 4.0.1 on 2022-05-10 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
