# Generated by Django 4.0.1 on 2022-05-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='defaultCode',
            field=models.TextField(default='', verbose_name='DefaultCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='tests',
            field=models.TextField(default='', verbose_name='Tests'),
            preserve_default=False,
        ),
    ]
