# Generated by Django 4.0.1 on 2022-05-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_tasks_defaultcode_tasks_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='defaultCode',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='tests',
        ),
        migrations.CreateModel(
            name='PythonTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField(verbose_name='Test')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.tasks')),
            ],
            options={
                'verbose_name': 'Python тест',
                'verbose_name_plural': 'Python тесты',
            },
        ),
        migrations.CreateModel(
            name='JsTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField(verbose_name='Test')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.tasks')),
            ],
            options={
                'verbose_name': 'Js тест',
                'verbose_name_plural': 'Js тесты',
            },
        ),
        migrations.CreateModel(
            name='GoTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField(verbose_name='Test')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.tasks')),
            ],
            options={
                'verbose_name': 'Go тест',
                'verbose_name_plural': 'Go тесты',
            },
        ),
    ]
