# Generated by Django 4.0.1 on 2022-05-10 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_tasks_created_at_tasks_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='difficulty',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskId',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
