# Generated by Django 4.0.1 on 2022-05-17 17:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_tasks_defaultcode_remove_tasks_tests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gotests',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.tasks', to_field='taskId'),
        ),
        migrations.AlterField(
            model_name='jstests',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.tasks', to_field='taskId'),
        ),
        migrations.AlterField(
            model_name='pythontests',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.tasks', to_field='taskId'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskId',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
