# Generated by Django 4.0.1 on 2022-05-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_gotests_task_alter_jstests_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gotests',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.tasks', to_field='taskId'),
        ),
        migrations.AlterField(
            model_name='jstests',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.tasks', to_field='taskId'),
        ),
        migrations.AlterField(
            model_name='pythontests',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.tasks', to_field='taskId'),
        ),
    ]
