# Generated by Django 4.0.1 on 2022-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_gotests_task_alter_jstests_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='reward',
            field=models.CharField(blank='{}', max_length=150),
        ),
    ]
