# Generated by Django 4.0.1 on 2022-05-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_aboutuser_passed_courses'),
        ('course', '0012_alter_gotests_task_alter_jstests_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20, verbose_name='lang')),
                ('testResult', models.TextField(verbose_name='result')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.tasks', to_field='taskId')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aboutuser')),
            ],
        ),
    ]
