# Generated by Django 4.0.1 on 2022-05-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_sessions'),
        ('course', '0015_alter_articles_options'),
    ]

    operations = [
    ]
