# Generated by Django 4.0.3 on 2022-04-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutuser',
            old_name='ex_to_level',
            new_name='exp_to_level',
        ),
    ]
