# Generated by Django 4.0.3 on 2022-04-05 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_rename_ex_to_level_aboutuser_exp_to_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='subs',
            field=models.ManyToManyField(default=[], related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
