# Generated by Django 4.0.1 on 2022-04-06 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_aboutuser_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='subs',
            field=models.ManyToManyField(default=[], related_name='subs_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
