# Generated by Django 3.2.3 on 2022-04-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_achievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuser',
            options={'verbose_name': 'данные пользователя', 'verbose_name_plural': 'данные пользователей'},
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'достижение', 'verbose_name_plural': 'достижения'},
        ),
    ]
