# Generated by Django 3.2.3 on 2022-04-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220407_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='achievements',
            field=models.ManyToManyField(default=[], related_name='achieve_owner', to='main.Achievement'),
        ),
    ]
