# Generated by Django 4.0.1 on 2022-04-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='activity',
            field=models.TextField(default='{}'),
        ),
    ]
