# Generated by Django 4.0.1 on 2022-04-25 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_aboutuser_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='skills',
            field=models.TextField(default='{"Basics": 0, "Algorithms": 0, "OOP": 0, "Data types": 0, "Collections": 0, "Python": 0, "GO": 0, "JS": 0}'),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='achievements',
            field=models.ManyToManyField(blank=True, default=[], related_name='achieve_owner', to='main.Achievement'),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='subs',
            field=models.ManyToManyField(blank=True, default=[], related_name='subs_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
