# Generated by Django 4.0.1 on 2022-04-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutuser_skills_alter_aboutuser_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='skills',
            field=models.TextField(default='{}'),
        ),
    ]
