# Generated by Django 4.0.1 on 2022-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_aboutuser_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='Items')),
            ],
            options={
                'verbose_name': 'Игровой товар',
                'verbose_name_plural': 'Игровые товары',
            },
        ),
    ]
