# Generated by Django 4.0.1 on 2022-05-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_gameitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='active_back',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_backs', to='main.gameitems'),
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='active_frame',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_frames', to='main.gameitems'),
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='inventory',
            field=models.ManyToManyField(blank=True, default=[], related_name='item_owner', to='main.GameItems'),
        ),
        migrations.AddField(
            model_name='gameitems',
            name='type',
            field=models.CharField(choices=[('fr', 'frame'), ('bg', 'background')], default='fr', max_length=30),
        ),
    ]
