# Generated by Django 4.0.1 on 2022-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_gameitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuser',
            name='active_back',
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='active_back',
            field=models.ManyToManyField(blank=True, null=True, related_name='set_backs', to='main.GameItems'),
        ),
        migrations.RemoveField(
            model_name='aboutuser',
            name='active_frame',
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='active_frame',
            field=models.ManyToManyField(blank=True, null=True, related_name='set_frames', to='main.GameItems'),
        ),
    ]
