# Generated by Django 4.0.1 on 2022-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_aboutuser_active_back_aboutuser_active_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='active_back',
            field=models.ManyToManyField(blank=True, related_name='set_backs', to='main.GameItems'),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='active_frame',
            field=models.ManyToManyField(blank=True, related_name='set_frames', to='main.GameItems'),
        ),
    ]
