# Generated by Django 4.0.1 on 2022-05-02 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_aboutuser_active_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuser',
            name='active_back',
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='active_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_backs', to='main.gameitems'),
        ),
        migrations.RemoveField(
            model_name='aboutuser',
            name='active_frame',
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='active_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_frame', to='main.gameitems'),
        ),
    ]
