# Generated by Django 4.0.1 on 2022-05-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_articles_required'),
        ('main', '0020_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='passed_courses',
            field=models.ManyToManyField(blank=True, default=[], to='course.Articles'),
        ),
    ]
