# Generated by Django 4.0.1 on 2022-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_achievement_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='condition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='achievement',
            name='money',
            field=models.SmallIntegerField(default=0),
        ),
    ]
