# Generated by Django 4.0.1 on 2022-05-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_aboutuser_passed_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ref',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
