# Generated by Django 4.0.4 on 2022-05-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='chevy_words',
            field=models.TextField(blank=True, max_length=500, verbose_name='Ключевые слова'),
        ),
    ]
