# Generated by Django 4.0.4 on 2022-05-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_questions_chevy_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='responses',
        ),
        migrations.DeleteModel(
            name='UserSteps',
        ),
    ]
