# Generated by Django 4.0.4 on 2022-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_questions_options_remove_questions_responses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.BigIntegerField(verbose_name='Номер темы')),
                ('keyword', models.CharField(blank=True, max_length=30, verbose_name='Ключевое слово')),
            ],
        ),
    ]
