# Generated by Django 4.0.4 on 2022-05-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ключевое слово'),
        ),
    ]
